# Order 30779295

This order contains a Trade Fill Cancel sequence where the Fill occurs on the SELL side at a lower price than the Cancel.

- The Cancel message implies that there is a resting order in the book.
- This is presumably a limit order.
- How can it be that the limit order on the SELL side is filled at a lower price than the limit price?

In [1]:
import pandas
import databento

In [2]:
pandas.set_option('display.max_rows', 50)
pandas.set_option('display.min_rows', 20)

In [3]:
def get_path(ticker, filename=None):
    ticker = 'nvda'
    #filename = 'xnas-itch-20240105.mbo.dbn.zst'
    return f'/databento/data/mbo/{ticker}/XNAS-20240622-WPPRESG4BH/{filename}'

In [4]:
full_path = get_path('nvda', filename='xnas-itch-20240105.mbo.dbn.zst')
full_path

'/databento/data/mbo/nvda/XNAS-20240622-WPPRESG4BH/xnas-itch-20240105.mbo.dbn.zst'

In [5]:
stored_data = databento.DBNStore.from_file(full_path)
df: pandas.DataFrame = stored_data.to_df().reset_index()

In [ ]:
df

In [33]:
df_selected = df[
    (df['order_id'] == 30779295) |
    (df['action'] == 'T')
].reset_index()

In [39]:
# Find the index of the first and last event related to this order_id
df_selected_order_id_30779295 = df_selected[df_selected['order_id'] == 30779295]
df_selected_order_id_30779295

,index,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,channel_id,order_id,flags,ts_in_delta,sequence,symbol
4704,119137,2024-01-05 14:30:38.697111950+00:00,2024-01-05 14:30:38.696945621+00:00,160,2,11667,A,A,485.76,30,0,30779295,130,166329,28201578,NVDA
4707,119142,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,F,A,485.75,30,0,30779295,130,167826,28201585,NVDA
4708,119143,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,C,A,485.76,30,0,30779295,130,167826,28201585,NVDA

In [40]:
INDEX_START = 4704
INDEX_STOP = 4708

In [35]:
len(df_selected)

103901

In [41]:
df_selected[INDEX_START-10:INDEX_STOP+10]

,index,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,channel_id,order_id,flags,ts_in_delta,sequence,symbol
4694,119055,2024-01-05 14:30:38.694989219+00:00,2024-01-05 14:30:38.694819055+00:00,160,2,11667,T,N,485.80,16,0,0,0,170164,28201424,NVDA
4695,119056,2024-01-05 14:30:38.694989219+00:00,2024-01-05 14:30:38.694819055+00:00,160,2,11667,T,N,485.80,6,0,0,128,170164,28201425,NVDA
4696,119075,2024-01-05 14:30:38.696466674+00:00,2024-01-05 14:30:38.696298373+00:00,160,2,11667,T,A,485.77,10,0,0,0,168301,28201474,NVDA
4697,119078,2024-01-05 14:30:38.696466674+00:00,2024-01-05 14:30:38.696298373+00:00,160,2,11667,T,A,485.77,25,0,0,130,168301,28201475,NVDA
4698,119098,2024-01-05 14:30:38.696955027+00:00,2024-01-05 14:30:38.696787595+00:00,160,2,11667,T,A,485.75,200,0,0,0,167432,28201521,NVDA
4699,119101,2024-01-05 14:30:38.696955027+00:00,2024-01-05 14:30:38.696787595+00:00,160,2,11667,T,A,485.75,59,0,0,130,167432,28201522,NVDA
4700,119105,2024-01-05 14:30:38.696999780+00:00,2024-01-05 14:30:38.696827505+00:00,160,2,11667,T,A,485.75,141,0,0,0,172275,28201530,NVDA
4701,119108,2024-01-05 14:30:38.696999780+00:00,2024-01-05 14:30:38.696827505+00:00,160,2,11667,T,A,485.75,200,0,0,0,172275,28201531,NVDA
4702,119125,2024-01-05 14:30:38.697077049+00:00,2024-01-05 14:30:38.696909628+00:00,160,2,11667,T,A,485.73,5,0,0,130,167421,28201562,NVDA
4703,119128,2024-01-05 14:30:38.697079991+00:00,2024-01-05 14:30:38.696912427+00:00,160,2,11667,T,A,485.73,10,0,0,130,167564,28201564,NVDA
4704,119137,2024-01-05 14:30:38.697111950+00:00,2024-01-05 14:30:38.696945621+00:00,160,2,11667,A,A,485.76,30,0,30779295,130,166329,28201578,NVDA
4705,119138,2024-01-05 14:30:38.697139982+00:00,2024-01-05 14:30:38.696971334+00:00,160,2,11667,T,A,485.74,15,0,0,130,168648,28201584,NVDA
4706,119141,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,T,B,485.75,30,0,0,130,167826,28201585,NVDA
4707,119142,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,F,A,485.75,30,0,30779295,130,167826,28201585,NVDA
4708,119143,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,C,A,485.76,30,0,30779295,130,167826,28201585,NVDA
4709,119152,2024-01-05 14:30:38.697233178+00:00,2024-01-05 14:30:38.697065409+00:00,160,2,11667,T,A,485.70,48,0,0,0,167769,28201599,NVDA
4710,119155,2024-01-05 14:30:38.697233178+00:00,2024-01-05 14:30:38.697065409+00:00,160,2,11667,T,A,485.69,71,0,0,130,167769,28201600,NVDA
4711,119168,2024-01-05 14:30:38.697771836+00:00,2024-01-05 14:30:38.697604983+00:00,160,2,11667,T,N,485.73,100,0,0,130,166853,28201646,NVDA
4712,119171,2024-01-05 14:30:38.697818004+00:00,2024-01-05 14:30:38.697651106+00:00,160,2,11667,T,N,485.73,29,0,0,130,166898,28201650,NVDA
4713,119185,2024-01-05 14:30:38.699684851+00:00,2024-01-05 14:30:38.699517423+00:00,160,2,11667,T,A,485.69,29,0,0,0,167428,28201704,NVDA
4714,119188,2024-01-05 14:30:38.699684851+00:00,2024-01-05 14:30:38.699517423+00:00,160,2,11667,T,A,485.68,11,0,0,130,167428,28201705,NVDA
4715,119191,2024-01-05 14:30:38.699706950+00:00,2024-01-05 14:30:38.699539108+00:00,160,2,11667,T,A,485.67,15,0,0,130,167842,28201706,NVDA
4716,119194,2024-01-05 14:30:38.699712898+00:00,2024-01-05 14:30:38.699544009+00:00,160,2,11667,T,A,485.67,35,0,0,0,168889,28201707,NVDA
4717,119197,2024-01-05 14:30:38.699712898+00:00,2024-01-05 14:30:38.699544009+00:00,160,2,11667,T,A,485.67,5,0,0,0,168889,28201708,NVDA

In [43]:
df_selected.iloc[INDEX_START:INDEX_START+1]

,index,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,channel_id,order_id,flags,ts_in_delta,sequence,symbol
4704,119137,2024-01-05 14:30:38.697111950+00:00,2024-01-05 14:30:38.696945621+00:00,160,2,11667,A,A,485.76,30,0,30779295,130,166329,28201578,NVDA

In [45]:
INDEX_START = 119137
INDEX_STOP = 119143

In [46]:
df[INDEX_START-10:INDEX_STOP+10]

,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,channel_id,order_id,flags,ts_in_delta,sequence,symbol
119127,2024-01-05 14:30:38.697077049+00:00,2024-01-05 14:30:38.696909628+00:00,160,2,11667,C,B,485.73,5,0,30770547,130,167421,28201562,NVDA
119128,2024-01-05 14:30:38.697079991+00:00,2024-01-05 14:30:38.696912427+00:00,160,2,11667,T,A,485.73,10,0,0,130,167564,28201564,NVDA
119129,2024-01-05 14:30:38.697079991+00:00,2024-01-05 14:30:38.696912427+00:00,160,2,11667,F,B,485.73,10,0,30770547,130,167564,28201564,NVDA
119130,2024-01-05 14:30:38.697079991+00:00,2024-01-05 14:30:38.696912427+00:00,160,2,11667,C,B,485.73,10,0,30770547,130,167564,28201564,NVDA
119131,2024-01-05 14:30:38.697093439+00:00,2024-01-05 14:30:38.696923015+00:00,160,2,11667,A,A,485.86,30,0,30779271,0,170424,28201569,NVDA
119132,2024-01-05 14:30:38.697093439+00:00,2024-01-05 14:30:38.696923280+00:00,160,2,11667,C,A,486.33,100,0,30759723,0,170159,28201570,NVDA
119133,2024-01-05 14:30:38.697093439+00:00,2024-01-05 14:30:38.696925567+00:00,160,2,11667,A,B,485.74,15,0,30779275,130,167872,28201571,NVDA
119134,2024-01-05 14:30:38.697102300+00:00,2024-01-05 14:30:38.696935470+00:00,160,2,11667,C,A,493.21,100,0,30778823,0,166830,28201573,NVDA
119135,2024-01-05 14:30:38.697102300+00:00,2024-01-05 14:30:38.696935470+00:00,160,2,11667,A,A,493.03,100,0,30779287,128,166830,28201573,NVDA
119136,2024-01-05 14:30:38.697111950+00:00,2024-01-05 14:30:38.696945621+00:00,160,2,11667,C,A,485.86,30,0,30779271,0,166329,28201578,NVDA
119137,2024-01-05 14:30:38.697111950+00:00,2024-01-05 14:30:38.696945621+00:00,160,2,11667,A,A,485.76,30,0,30779295,130,166329,28201578,NVDA
119138,2024-01-05 14:30:38.697139982+00:00,2024-01-05 14:30:38.696971334+00:00,160,2,11667,T,A,485.74,15,0,0,130,168648,28201584,NVDA
119139,2024-01-05 14:30:38.697139982+00:00,2024-01-05 14:30:38.696971334+00:00,160,2,11667,F,B,485.74,15,0,30779275,130,168648,28201584,NVDA
119140,2024-01-05 14:30:38.697139982+00:00,2024-01-05 14:30:38.696971334+00:00,160,2,11667,C,B,485.74,15,0,30779275,130,168648,28201584,NVDA
119141,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,T,B,485.75,30,0,0,130,167826,28201585,NVDA
119142,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,F,A,485.75,30,0,30779295,130,167826,28201585,NVDA
119143,2024-01-05 14:30:38.697147649+00:00,2024-01-05 14:30:38.696979823+00:00,160,2,11667,C,A,485.76,30,0,30779295,130,167826,28201585,NVDA
119144,2024-01-05 14:30:38.697150954+00:00,2024-01-05 14:30:38.696984954+00:00,160,2,11667,C,A,493.03,100,0,30779287,0,166000,28201586,NVDA
119145,2024-01-05 14:30:38.697150954+00:00,2024-01-05 14:30:38.696984954+00:00,160,2,11667,A,A,493.21,100,0,30779323,130,166000,28201586,NVDA
119146,2024-01-05 14:30:38.697163788+00:00,2024-01-05 14:30:38.696998121+00:00,160,2,11667,C,B,485.66,18,0,30779239,130,165667,28201588,NVDA
119147,2024-01-05 14:30:38.697181139+00:00,2024-01-05 14:30:38.697014899+00:00,160,2,11667,A,B,485.70,48,0,30779339,130,166240,28201590,NVDA
119148,2024-01-05 14:30:38.697201240+00:00,2024-01-05 14:30:38.697034826+00:00,160,2,11667,C,A,493.21,100,0,30779323,0,166414,28201593,NVDA
119149,2024-01-05 14:30:38.697201240+00:00,2024-01-05 14:30:38.697034826+00:00,160,2,11667,A,A,493.00,100,0,30779351,130,166414,28201593,NVDA
119150,2024-01-05 14:30:38.697213487+00:00,2024-01-05 14:30:38.697047258+00:00,160,2,11667,C,B,478.51,100,0,30779251,0,166229,28201595,NVDA
119151,2024-01-05 14:30:38.697213487+00:00,2024-01-05 14:30:38.697047258+00:00,160,2,11667,A,B,478.45,100,0,30779363,130,166229,28201595,NVDA
119152,2024-01-05 14:30:38.697233178+00:00,2024-01-05 14:30:38.697065409+00:00,160,2,11667,T,A,485.70,48,0,0,0,167769,28201599,NVDA